// Feedbacks services
const MEDIA_SERVICE_ROUTES_PATH = "/media";
const USERS_SERVICE_ROUTES_PATH = "/profile";
const FEEDBACKS_SERVICE_ROUTES_PATH = "/feedbacks";
const AUTHENTICATION_SERVICE_ROUTES_PATH = "/authentication";
const BACKOFFICE_USERS_SERVICE_ROUTES_PATH = "/feedbacks/backoffice";

module.exports = {
    USERS_SERVICE_ROUTES_PATH,
    MEDIA_SERVICE_ROUTES_PATH,
    FEEDBACKS_SERVICE_ROUTES_PATH,
    BACKOFFICE_USERS_SERVICE_ROUTES_PATH,
    AUTHENTICATION_SERVICE_ROUTES_PATH,
}
