// Feedbacks services
const MEDIA_SERVICE_ROUTES_PATH = "/media";
const USERS_SERVICE_ROUTES_PATH = "/profile";
const FEEDBACK_SERVICE_ROUTES_PATH = "/feedbacks";
const BACKOFFICE_USERS_SERVICE_ROUTES_PATH = "/auth";

module.exports = {
    USERS_SERVICE_ROUTES_PATH,
    MEDIA_SERVICE_ROUTES_PATH,
    FEEDBACK_SERVICE_ROUTES_PATH,
    BACKOFFICE_USERS_SERVICE_ROUTES_PATH,
}