// Response messages
const AUTH_FAILED = 'AUTH_FAILED';
const USER_NOT_FOUND = 'USER_NOT_FOUND';
const CASE_NOT_FOUND = 'CASE_NOT_FOUND';
const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
const FORM_DATA_ERROR = 'FORM_DATA_ERROR';
const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
const MESSAGES_NOT_FAILED = 'MESSAGES_NOT_FAILED';
const INVALID_TOKEN_ERROR = 'INVALID_TOKEN_ERROR';
const DATABASE_SERVER_ERROR = 'DATABASE_SERVER_ERROR';
const BACKOFFICE_USER_NOT_FOUND = 'BACKOFFICE_USER_NOT_FOUND';
const UNAUTHORIZED_REQUEST_ERROR = 'UNAUTHORIZED_REQUEST_ERROR';

module.exports = {
    AUTH_FAILED,
    CASE_NOT_FOUND,
    USER_NOT_FOUND,
    USER_LOGGED_OUT,
    FORM_DATA_ERROR,
    USER_AUTHENTICATED,
    INVALID_TOKEN_ERROR,
    MESSAGES_NOT_FAILED,
    DATABASE_SERVER_ERROR,
    BACKOFFICE_USER_NOT_FOUND,
    UNAUTHORIZED_REQUEST_ERROR,
}