// Response messages
const INVALID_TOKEN_ERROR = 'INVALID_TOKEN_ERROR';
const UNAUTHORIZED_REQUEST_ERROR = 'UNAUTHORIZED_REQUEST_ERROR';

module.exports.INVALID_TOKEN_ERROR = INVALID_TOKEN_ERROR;
module.exports.UNAUTHORIZED_REQUEST_ERROR = UNAUTHORIZED_REQUEST_ERROR;
