// Response messages
const AUTH_FAILED = 'AUTH_FAILED';
const USER_NOT_FOUND = 'USER_NOT_FOUND';
const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
const FORM_DATA_ERROR = 'FORM_DATA_ERROR';
const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
const INVALID_TOKEN_ERROR = 'INVALID_TOKEN_ERROR';
const DATABASE_SERVER_ERROR = 'DATABASE_SERVER_ERROR';
const UNAUTHORIZED_REQUEST_ERROR = 'UNAUTHORIZED_REQUEST_ERROR';

module.exports.AUTH_FAILED = AUTH_FAILED;
module.exports.USER_NOT_FOUND = USER_NOT_FOUND;
module.exports.USER_LOGGED_OUT = USER_LOGGED_OUT;
module.exports.FORM_DATA_ERROR = FORM_DATA_ERROR;
module.exports.FORM_DATA_ERROR = FORM_DATA_ERROR;
module.exports.USER_AUTHENTICATED = USER_AUTHENTICATED;
module.exports.INVALID_TOKEN_ERROR = INVALID_TOKEN_ERROR;
module.exports.DATABASE_SERVER_ERROR = DATABASE_SERVER_ERROR;
module.exports.UNAUTHORIZED_REQUEST_ERROR = UNAUTHORIZED_REQUEST_ERROR;
